services:
  portrayt:
    image: alexthiel/portrayt
    command: poetry run run-portrayt --port 80 --renderer ${RENDERER:-opencv}
    privileged: true
    restart: unless-stopped
    volumes:
      # Necessary for display passthrough
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      # State
      - "./.portrayt-state:/project/.portrayt-state"
    environment:
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
      # Necessary for display passthrough
      DISPLAY: $DISPLAY
    build:
      context: .
      args:
        POETRY_EXTRAS: ${POETRY_EXTRAS:-}
    ports:
      - 80:80
